#!/usr/bin/env python3

import sys
import os
import helpers
from analyzer import Analyzer
from termcolor import colored

# TODO
def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets name")

    screen_name = sys.argv[1].strip('@')

    timeline = helpers.get_user_timeline(screen_name, 50)

    if timeline == None:
        sys.exit("User is private or doesn't exist")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)


    for tweet in timeline:
        score = analyzer.analyze(tweet)

        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))


if __name__ == "__main__":
    main()

